In [11]:
# ============================================
# STEP 1.1 — Import Libraries & Define Paths
# ============================================

import pandas as pd
import numpy as np
from pathlib import Path

# Project root
PROJECT_ROOT = Path.cwd().parent

# Raw data folder
RAW_DATA = PROJECT_ROOT / "Data" / "raw data"

# Dataset paths
AIR_FILE = RAW_DATA / "air_quality_2019_2021_hourly.csv"
MET_FILE = RAW_DATA / "hourly_meteorology_16stations_2019_2021(2).csv"

print("Project Root:")
print(PROJECT_ROOT)

print("\nRaw Data Folder:")
print(RAW_DATA)

print("\nAir Quality File:")
print(AIR_FILE)

print("\nMeteorology File:")
print(MET_FILE)

Project Root:
e:\Edge_air_pollution imputation

Raw Data Folder:
e:\Edge_air_pollution imputation\Data\raw data

Air Quality File:
e:\Edge_air_pollution imputation\Data\raw data\air_quality_2019_2021_hourly.csv

Meteorology File:
e:\Edge_air_pollution imputation\Data\raw data\hourly_meteorology_16stations_2019_2021(2).csv

In [12]:
# ============================================
# STEP 1.2A — Check Files in Raw Data Folder
# ============================================

print("Files available in raw data folder:\n")

for file in RAW_DATA.iterdir():
    print(file.name)

Files available in raw data folder:

air_quality_2019_2021_hourly.csv
hourly_meteorology_16stations_2019_2021.csv

In [13]:
# ============================================
# STEP 1.2 — Load Both Datasets
# ============================================

# Correct Meteorology file path
MET_FILE = RAW_DATA / "hourly_meteorology_16stations_2019_2021.csv"

# Load Air Quality dataset
air_df = pd.read_csv(AIR_FILE)

# Load Meteorology dataset
met_df = pd.read_csv(MET_FILE)

# Display dataset shapes
print("Air Quality Dataset Shape:")
print(air_df.shape)

print("\nMeteorology Dataset Shape:")
print(met_df.shape)

Air Quality Dataset Shape:
(420864, 10)

Meteorology Dataset Shape:
(420864, 9)

In [14]:
# ============================================
# STEP 1.3 — Check Columns and Sample Data
# ============================================

print("AIR QUALITY COLUMNS:")
print(air_df.columns.tolist())

print("\nAIR QUALITY SAMPLE:")
display(air_df.head())

print("\n" + "=" * 60)

print("\nMETEOROLOGY COLUMNS:")
print(met_df.columns.tolist())

print("\nMETEOROLOGY SAMPLE:")
display(met_df.head())

AIR QUALITY COLUMNS:
['station_id', 'station_name', 'timestamp', 'pm25', 'pm10', 'no2', 'o3', 'so2', 'nox', 'co']

AIR QUALITY SAMPLE:

,station_id,station_name,timestamp,pm25,pm10,no2,o3,so2,nox,co
0,71,CAUSEWAY BAY,2019-01-01 00:00:00,31.0,42.0,67.0,2.0,9.0,299.0,93.0
1,71,CAUSEWAY BAY,2019-01-01 01:00:00,31.0,41.0,60.0,3.0,5.0,184.0,90.0
2,71,CAUSEWAY BAY,2019-01-01 02:00:00,27.0,36.0,40.0,7.0,3.0,70.0,80.0
3,71,CAUSEWAY BAY,2019-01-01 03:00:00,NaN,NaN,37.0,9.0,3.0,70.0,79.0
4,71,CAUSEWAY BAY,2019-01-01 04:00:00,NaN,NaN,29.0,11.0,3.0,56.0,74.0

============================================================

METEOROLOGY COLUMNS:
['station_id', 'station_name', 'timestamp', 'temperature', 'relative_humidity', 'wind_speed', 'wind_direction', 'pressure', 'rainfall']

METEOROLOGY SAMPLE:

,station_id,station_name,timestamp,temperature,relative_humidity,wind_speed,wind_direction,pressure,rainfall
0,71,CAUSEWAY BAY,2019-01-01 00:00:00,8.6,72,5.33,6,1025.0,0.0
1,71,CAUSEWAY BAY,2019-01-01 01:00:00,8.3,73,5.47,9,1024.8,0.0
2,71,CAUSEWAY BAY,2019-01-01 02:00:00,7.9,74,5.69,10,1024.2,0.0
3,71,CAUSEWAY BAY,2019-01-01 03:00:00,7.7,73,5.67,9,1023.6,0.0
4,71,CAUSEWAY BAY,2019-01-01 04:00:00,7.4,73,5.79,10,1023.4,0.0

In [15]:
# ============================================
# STEP 1.4 — Convert Timestamp & Check Time Range
# ============================================

# Convert timestamp columns to datetime
air_df["timestamp"] = pd.to_datetime(air_df["timestamp"])
met_df["timestamp"] = pd.to_datetime(met_df["timestamp"])

# Display time range
print("AIR QUALITY TIME RANGE")
print("Start:", air_df["timestamp"].min())
print("End  :", air_df["timestamp"].max())

print("\nMETEOROLOGY TIME RANGE")
print("Start:", met_df["timestamp"].min())
print("End  :", met_df["timestamp"].max())

# Number of unique timestamps
print("\nUnique timestamps:")
print("Air Quality:", air_df["timestamp"].nunique())
print("Meteorology:", met_df["timestamp"].nunique())

AIR QUALITY TIME RANGE
Start: 2019-01-01 00:00:00
End  : 2021-12-31 23:00:00

METEOROLOGY TIME RANGE
Start: 2019-01-01 00:00:00
End  : 2021-12-31 23:00:00

Unique timestamps:
Air Quality: 26304
Meteorology: 26304

In [16]:
# ============================================
# STEP 1.5 — Verify Stations
# ============================================

air_stations = sorted(air_df["station_id"].unique())
met_stations = sorted(met_df["station_id"].unique())

print("Air Quality Stations:")
print(air_stations)

print("\nNumber of Air Quality Stations:")
print(len(air_stations))

print("\nMeteorology Stations:")
print(met_stations)

print("\nNumber of Meteorology Stations:")
print(len(met_stations))

# Check whether both datasets have exactly the same stations
print("\nDo both datasets have the same stations?")
print(air_stations == met_stations)

Air Quality Stations:
[np.int64(66), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(74), np.int64(75), np.int64(76), np.int64(77), np.int64(78), np.int64(79), np.int64(80), np.int64(81), np.int64(82), np.int64(83)]

Number of Air Quality Stations:
16

Meteorology Stations:
[np.int64(66), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(74), np.int64(75), np.int64(76), np.int64(77), np.int64(78), np.int64(79), np.int64(80), np.int64(81), np.int64(82), np.int64(83)]

Number of Meteorology Stations:
16

Do both datasets have the same stations?
True

In [17]:
# ============================================
# STEP 1.6 — Check Duplicate Station-Timestamp
# ============================================

# Check duplicates in Air Quality dataset
air_duplicates = air_df.duplicated(
    subset=["station_id", "timestamp"]
).sum()

# Check duplicates in Meteorology dataset
met_duplicates = met_df.duplicated(
    subset=["station_id", "timestamp"]
).sum()

print("Air Quality duplicate station-timestamp records:")
print(air_duplicates)

print("\nMeteorology duplicate station-timestamp records:")
print(met_duplicates)

Air Quality duplicate station-timestamp records:
0

Meteorology duplicate station-timestamp records:
0

In [18]:
# ============================================
# STEP 1.7 — Merge Air Quality + Meteorology
# ============================================

# Merge both datasets
merged_df = pd.merge(
    air_df,
    met_df,
    on=["station_id", "station_name", "timestamp"],
    how="inner",
    suffixes=("_air", "_met")
)

# Display merged dataset shape
print("Merged Dataset Shape:")
print(merged_df.shape)

# Display columns
print("\nMerged Dataset Columns:")
print(merged_df.columns.tolist())

Merged Dataset Shape:
(420864, 16)

Merged Dataset Columns:
['station_id', 'station_name', 'timestamp', 'pm25', 'pm10', 'no2', 'o3', 'so2', 'nox', 'co', 'temperature', 'relative_humidity', 'wind_speed', 'wind_direction', 'pressure', 'rainfall']

In [19]:
# ============================================
# STEP 1.8 — Verify 13 Model Features
# ============================================

# Air pollution features
pollution_features = [
    "pm25",
    "pm10",
    "no2",
    "o3",
    "so2",
    "nox",
    "co"
]

# Meteorological features
weather_features = [
    "temperature",
    "relative_humidity",
    "wind_speed",
    "wind_direction",
    "pressure",
    "rainfall"
]

# Combine all model features
feature_columns = pollution_features + weather_features

print("Air Pollution Features:")
print(pollution_features)
print("Count:", len(pollution_features))

print("\nMeteorological Features:")
print(weather_features)
print("Count:", len(weather_features))

print("\nTotal Model Features:")
print(feature_columns)
print("Total Count:", len(feature_columns))

# Verify all features exist in merged dataset
missing_features = [
    feature for feature in feature_columns
    if feature not in merged_df.columns
]

print("\nMissing Features:")
print(missing_features)

print("\n13 Features Verified:")
print(len(feature_columns) == 13 and len(missing_features) == 0)

Air Pollution Features:
['pm25', 'pm10', 'no2', 'o3', 'so2', 'nox', 'co']
Count: 7

Meteorological Features:
['temperature', 'relative_humidity', 'wind_speed', 'wind_direction', 'pressure', 'rainfall']
Count: 6

Total Model Features:
['pm25', 'pm10', 'no2', 'o3', 'so2', 'nox', 'co', 'temperature', 'relative_humidity', 'wind_speed', 'wind_direction', 'pressure', 'rainfall']
Total Count: 13

Missing Features:
[]

13 Features Verified:
True

# Data cleaning

In [20]:
# ============================================
# STEP 2.1 — Check Missing Values
# ============================================

missing_counts = merged_df.isna().sum()

print("Missing Values in Each Column:")
print(missing_counts)

print("\nTotal Missing Values:")
print(missing_counts.sum())

Missing Values in Each Column:
station_id                0
station_name              0
timestamp                 0
pm25                  10657
pm10                  11395
no2                   11651
o3                    11117
so2                   11056
nox                   37447
co                   190788
temperature               0
relative_humidity         0
wind_speed                0
wind_direction            0
pressure                  0
rainfall                  0
dtype: int64

Total Missing Values:
284111

In [21]:
# ============================================
# STEP 2.2 — Calculate Missing Percentage
# ============================================

# Calculate missing percentage for each model feature
missing_percentage = (
    merged_df[feature_columns]
    .isna()
    .mean()
    * 100
)

# Create summary table
missing_summary = pd.DataFrame({
    "Missing_Count": merged_df[feature_columns].isna().sum(),
    "Missing_Percentage": missing_percentage
})

# Sort by missing count
missing_summary = missing_summary.sort_values(
    by="Missing_Count",
    ascending=False
)

print("Missing Value Summary:")
display(missing_summary)

Missing Value Summary:

                   Missing_Count  Missing_Percentage
co                        190788           45.332459
nox                        37447            8.897649
no2                        11651            2.768353
pm10                       11395            2.707525
o3                         11117            2.641471
so2                        11056            2.626977
pm25                       10657            2.532172
temperature                    0            0.000000
relative_humidity              0            0.000000
wind_speed                     0            0.000000
wind_direction                 0            0.000000
pressure                       0            0.000000
rainfall                       0            0.000000

In [22]:
# ============================================
# STEP 2.3 — Station-wise Missing Values
# ============================================

# Calculate total missing values for each station
station_missing = (
    merged_df
    .groupby(["station_id", "station_name"])[feature_columns]
    .apply(lambda x: x.isna().sum().sum())
    .reset_index(name="Missing_Count")
)

# Calculate total possible feature values per station
total_values_per_station = (
    merged_df.groupby(["station_id", "station_name"]).size()
    * len(feature_columns)
)

# Add total values
station_missing["Total_Values"] = (
    station_missing.set_index(["station_id", "station_name"]).index
    .map(total_values_per_station)
)

# Calculate missing percentage
station_missing["Missing_Percentage"] = (
    station_missing["Missing_Count"]
    / station_missing["Total_Values"]
    * 100
)

# Sort by missing percentage
station_missing = station_missing.sort_values(
    "Missing_Percentage",
    ascending=False
)

display(station_missing)

,station_id,station_name,Missing_Count,Total_Values,Missing_Percentage
5,73,EASTERN,56220,341952,16.440904
7,75,SHATIN,31864,341952,9.318267
0,66,SHAM SHUI PO,31427,341952,9.190471
6,74,KWUN TONG,31130,341952,9.103617
4,72,KWAI CHUNG,30090,341952,8.799481
1,69,TAI PO,29370,341952,8.588925
12,80,CENTRAL/WESTERN,29297,341952,8.567577
8,76,TAP MUN,6933,341952,2.027478
2,70,YUEN LONG,6139,341952,1.795281
9,77,TSUEN WAN,6027,341952,1.762528
10,78,TUNG CHUNG,6024,341952,1.761651
3,71,CAUSEWAY BAY,4990,341952,1.459269
13,81,MONG KOK,4156,341952,1.215375
11,79,CENTRAL,3955,341952,1.156595
15,83,TSEUNG KWAN O,3301,341952,0.965340
14,82,TUEN MUN,3188,341952,0.932295

In [23]:
# ============================================
# STEP 2.4 — Check Completely Missing
# Feature-Station Combinations
# ============================================

# Calculate missing values for each station and feature
station_feature_missing = (
    merged_df
    .groupby(["station_id", "station_name"])[feature_columns]
    .apply(lambda x: x.isna().sum())
)

# Find station-feature combinations where ALL values are missing
completely_missing = []

for station in station_feature_missing.index:
    for feature in feature_columns:
        missing_count = station_feature_missing.loc[station, feature]
        
        if missing_count == 26304:
            completely_missing.append({
                "station_id": station[0],
                "station_name": station[1],
                "feature": feature,
                "missing_count": missing_count
            })

completely_missing_df = pd.DataFrame(completely_missing)

print("Completely Missing Station-Feature Combinations:")
display(completely_missing_df)

print("\nTotal Completely Missing Combinations:")
print(len(completely_missing_df))

Completely Missing Station-Feature Combinations:

   station_id     station_name feature  missing_count
0          66     SHAM SHUI PO      co          26304
1          69           TAI PO      co          26304
2          72       KWAI CHUNG      co          26304
3          73          EASTERN     nox          26304
4          73          EASTERN      co          26304
5          74        KWUN TONG      co          26304
6          75           SHATIN      co          26304
7          80  CENTRAL/WESTERN      co          26304

Total Completely Missing Combinations:
8

In [24]:
# ============================================
# STEP 2.5 — Feature-wise Missingness by Station
# ============================================

station_feature_summary = (
    merged_df
    .groupby(["station_id", "station_name"])[feature_columns]
    .apply(lambda x: x.isna().mean() * 100)
)

print("Missing Percentage (%) for Each Feature at Each Station:")

display(
    station_feature_summary.round(2)
)

Missing Percentage (%) for Each Feature at Each Station:

,,pm25,pm10,no2,o3,so2,nox,co,temperature,relative_humidity,wind_speed,wind_direction,pressure,rainfall
station_id,station_name,,,,,,,,,,,,,
66,SHAM SHUI PO,3.19,2.63,3.49,3.74,2.93,3.49,100.00,0.0,0.0,0.0,0.0,0.0,0.0
69,TAI PO,2.11,2.10,2.19,1.03,2.03,2.19,100.00,0.0,0.0,0.0,0.0,0.0,0.0
70,YUEN LONG,2.43,2.23,4.08,3.58,3.43,4.08,3.52,0.0,0.0,0.0,0.0,0.0,0.0
71,CAUSEWAY BAY,3.41,3.41,2.43,2.07,2.64,2.43,2.59,0.0,0.0,0.0,0.0,0.0,0.0
72,KWAI CHUNG,2.19,2.15,2.38,3.10,2.21,2.38,100.00,0.0,0.0,0.0,0.0,0.0,0.0
73,EASTERN,4.20,3.86,1.93,1.86,1.87,100.00,100.00,0.0,0.0,0.0,0.0,0.0,0.0
74,KWUN TONG,2.12,6.13,2.37,2.97,2.39,2.37,100.00,0.0,0.0,0.0,0.0,0.0,0.0
75,SHATIN,4.81,4.94,3.05,3.01,2.28,3.05,100.00,0.0,0.0,0.0,0.0,0.0,0.0
76,TAP MUN,2.26,2.41,4.46,4.17,4.09,4.46,4.49,0.0,0.0,0.0,0.0,0.0,0.0
77,TSUEN WAN,1.87,1.87,4.00,3.70,3.70,4.00,3.79,0.0,0.0,0.0,0.0,0.0,0.0
78,TUNG CHUNG,1.85,1.84,3.89,3.88,3.82,3.89,3.74,0.0,0.0,0.0,0.0,0.0,0.0
79,CENTRAL,3.28,3.28,1.91,0.73,1.97,1.91,1.97,0.0,0.0,0.0,0.0,0.0,0.0
80,CENTRAL/WESTERN,1.15,1.16,2.30,1.85,2.62,2.30,100.00,0.0,0.0,0.0,0.0,0.0,0.0
81,MONG KOK,1.03,1.03,2.89,2.92,2.62,2.89,2.42,0.0,0.0,0.0,0.0,0.0,0.0
82,TUEN MUN,2.71,2.42,1.33,1.89,1.40,1.33,1.04,0.0,0.0,0.0,0.0,0.0,0.0
83,TSEUNG KWAN O,1.91,1.86,1.61,1.76,2.02,1.61,1.78,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
# ============================================
# STEP 2.6 — Final Data Quality Check
# ============================================

# 1. Duplicate complete rows
duplicate_rows = merged_df.duplicated().sum()

# 2. Invalid / missing timestamps
missing_timestamps = merged_df["timestamp"].isna().sum()

# 3. Infinite values in numeric feature columns
infinite_values = np.isinf(
    merged_df[feature_columns].select_dtypes(include=np.number)
).sum().sum()

print("FINAL DATA QUALITY CHECK")
print("--------------------------------")
print("Duplicate complete rows :", duplicate_rows)
print("Missing timestamps      :", missing_timestamps)
print("Infinite values         :", infinite_values)

FINAL DATA QUALITY CHECK
--------------------------------
Duplicate complete rows : 0
Missing timestamps      : 0
Infinite values         : 0

# Missing-Value Masking

In [26]:
# ============================================
# STEP 3.1 — Create Original Observation Mask
# ============================================

# 1 = value originally available
# 0 = value originally missing

original_observation_mask = (
    merged_df[feature_columns]
    .notna()
    .astype("int8")
)

print("Original Observation Mask Shape:")
print(original_observation_mask.shape)

print("\nMask Values:")
print(original_observation_mask.stack().value_counts())

print("\n1 = Originally Observed")
print("0 = Originally Missing")

Original Observation Mask Shape:
(420864, 13)

Mask Values:
1    5187121
0     284111
Name: count, dtype: int64

1 = Originally Observed
0 = Originally Missing

In [27]:
# ============================================
# STEP 3.2 — Create Artificial Missing Mask
# ============================================

np.random.seed(42)

missing_rate = 0.20

# Copy original observation mask
artificial_mask_array = original_observation_mask.to_numpy(copy=True)

# Generate random values
random_values = np.random.random(
    artificial_mask_array.shape
)

# Select only originally observed values
artificial_positions = (
    (artificial_mask_array == 1) &
    (random_values < missing_rate)
)

# Mark selected values as artificially missing
artificial_mask_array[artificial_positions] = 0

# Convert back to DataFrame
artificial_mask = pd.DataFrame(
    artificial_mask_array,
    index=merged_df.index,
    columns=feature_columns
)

print("Artificial Mask Shape:")
print(artificial_mask.shape)

print("\nArtificial Mask Values:")
print(artificial_mask.stack().value_counts())

print("\nArtificially Masked Values:")
print(artificial_positions.sum())

Artificial Mask Shape:
(420864, 13)

Artificial Mask Values:
1    4149666
0    1321566
Name: count, dtype: int64

Artificially Masked Values:
1037455

In [29]:
# ============================================
# STEP 3.3 — Correctly Verify Artificial Mask
# ============================================

# Positions that were artificially masked
artificially_masked = (
    (original_observation_mask == 1) &
    (artificial_mask == 0)
)

# Check whether every artificially masked value
# was originally observed
invalid_artificial_masks = (
    (original_observation_mask == 0) &
    artificially_masked
)

print("Artificially Masked Values:")
print(artificially_masked.to_numpy().sum())

print("\nInvalid Artificial Masks:")
print(invalid_artificial_masks.to_numpy().sum())

print("\nMask Verification:")

if invalid_artificial_masks.to_numpy().sum() == 0:
    print("PASS")
else:
    print("FAIL")

Artificially Masked Values:
1037455

Invalid Artificial Masks:
0

Mask Verification:
PASS

In [30]:
# ============================================
# STEP 3.4 — Save Fixed Artificial Mask
# ============================================

PROCESSED_DATA = PROJECT_ROOT / "Data" / "processed"

# Create processed folder if it does not exist
PROCESSED_DATA.mkdir(parents=True, exist_ok=True)

# Save the fixed artificial mask
MASK_FILE = PROCESSED_DATA / "fixed_artificial_mask_new.csv"

artificial_mask.to_csv(
    MASK_FILE,
    index=False
)

print("Fixed Artificial Mask Saved Successfully!")
print("\nFile:")
print(MASK_FILE)

print("\nShape:")
print(artificial_mask.shape)

Fixed Artificial Mask Saved Successfully!

File:
e:\Edge_air_pollution imputation\Data\processed\fixed_artificial_mask_new.csv

Shape:
(420864, 13)

# Sliding-Window Dataset Creation

In [31]:
# ============================================
# STEP 4.1 — Create Data Tensor
# ============================================

# Sort data properly
merged_df = merged_df.sort_values(
    ["timestamp", "station_id"]
).reset_index(drop=True)

# Get ordered timestamps and stations
timestamps = sorted(merged_df["timestamp"].unique())
stations = sorted(merged_df["station_id"].unique())

# Create 3D data tensor
data_tensor = np.full(
    (len(timestamps), len(stations), len(feature_columns)),
    np.nan,
    dtype=np.float32
)

# Fill tensor
for t_idx, timestamp in enumerate(timestamps):
    timestamp_data = merged_df[
        merged_df["timestamp"] == timestamp
    ].sort_values("station_id")

    data_tensor[t_idx, :, :] = (
        timestamp_data[feature_columns]
        .to_numpy(dtype=np.float32)
    )

print("Data Tensor Shape:")
print(data_tensor.shape)

print("\nExpected Shape:")
print("(26304, 16, 13)")

print("\nShape Verification:")
print(data_tensor.shape == (26304, 16, 13))

Data Tensor Shape:
(26304, 16, 13)

Expected Shape:
(26304, 16, 13)

Shape Verification:
True

In [32]:
# ============================================
# STEP 4.2 — Create Mask Tensor
# ============================================

# Convert fixed artificial mask into numpy array
mask_array = artificial_mask.to_numpy(
    dtype=np.int8
)

# Create mask tensor
mask_tensor = np.full(
    (len(timestamps), len(stations), len(feature_columns)),
    0,
    dtype=np.int8
)

# Fill mask tensor
for t_idx, timestamp in enumerate(timestamps):
    timestamp_mask = merged_df[
        merged_df["timestamp"] == timestamp
    ].sort_values("station_id")

    mask_tensor[t_idx, :, :] = (
        artificial_mask.loc[
            timestamp_mask.index,
            feature_columns
        ]
        .to_numpy(dtype=np.int8)
    )

print("Mask Tensor Shape:")
print(mask_tensor.shape)

print("\nExpected Shape:")
print("(26304, 16, 13)")

print("\nShape Verification:")
print(mask_tensor.shape == (26304, 16, 13))

print("\nMask Values:")
print(
    np.unique(
        mask_tensor,
        return_counts=True
    )
)

Mask Tensor Shape:
(26304, 16, 13)

Expected Shape:
(26304, 16, 13)

Shape Verification:
True

Mask Values:
(array([0, 1], dtype=int8), array([1321566, 4149666]))

In [33]:
# ============================================
# STEP 4.3 — Create 24-Hour Sliding Windows
# ============================================

WINDOW_SIZE = 24

# Create data sliding windows
data_windows = np.array([
    data_tensor[i:i + WINDOW_SIZE]
    for i in range(
        len(data_tensor) - WINDOW_SIZE + 1
    )
])

# Create corresponding mask sliding windows
mask_windows = np.array([
    mask_tensor[i:i + WINDOW_SIZE]
    for i in range(
        len(mask_tensor) - WINDOW_SIZE + 1
    )
])

print("Data Windows Shape:")
print(data_windows.shape)

print("\nMask Windows Shape:")
print(mask_windows.shape)

print("\nExpected Shape:")
print("(26281, 24, 16, 13)")

print("\nData Shape Verification:")
print(data_windows.shape == (26281, 24, 16, 13))

print("\nMask Shape Verification:")
print(mask_windows.shape == (26281, 24, 16, 13))

Data Windows Shape:
(26281, 24, 16, 13)

Mask Windows Shape:
(26281, 24, 16, 13)

Expected Shape:
(26281, 24, 16, 13)

Data Shape Verification:
True

Mask Shape Verification:
True

In [34]:
# ============================================
# STEP 4.4 — Final Sliding-Window Verification
# ============================================

print("DATA WINDOWS")
print("Shape:", data_windows.shape)
print("NaN Count:", np.isnan(data_windows).sum())

print("\nMASK WINDOWS")
print("Shape:", mask_windows.shape)
print("Unique Values:", np.unique(mask_windows))

print("\nALIGNMENT CHECK")
print(
    "Same Number of Windows:",
    data_windows.shape[0] == mask_windows.shape[0]
)

print(
    "Same Time Window:",
    data_windows.shape[1] == mask_windows.shape[1]
)

print(
    "Same Stations:",
    data_windows.shape[2] == mask_windows.shape[2]
)

print(
    "Same Features:",
    data_windows.shape[3] == mask_windows.shape[3]
)

DATA WINDOWS
Shape: (26281, 24, 16, 13)
NaN Count: 6813327

MASK WINDOWS
Shape: (26281, 24, 16, 13)
Unique Values: [0 1]

ALIGNMENT CHECK
Same Number of Windows: True
Same Time Window: True
Same Stations: True
Same Features: True