In [2]:
import os

print(os.getcwd())

E:\Edge_air_pollution imputation\Notebook

In [4]:
import os

os.listdir("..")

['.git',
 '.gitignore',
 'Data',
 'deployment',
 'distillation',
 'evaluation',
 'Models',
 'Notebook',
 'preprocessing',
 'README.md',
 'requirements.txt',
 'Results',
 'src',
 'venv']

In [5]:
os.listdir("../Data")

['raw data']

In [7]:
os.listdir("../Data/raw data")

['air_weather_hourly_2019_2021 (2).csv']

In [8]:
import pandas as pd

df = pd.read_csv("../Data/raw data/air_weather_hourly_2019_2021 (2).csv")

df.head()

,DATE,HOUR,POLLUTANT,SHATIN,TSUEN WAN,CENTRAL,EASTERN,KWUN TONG,TUEN MUN,TUNG CHUNG,...,TAI PO,MONG KOK,CAUSEWAY BAY,TIMESTAMP,Temperature_mean,Humidity_mean,Sea_Level_Pressure_mean,Wind_Speed_mean,Available_Stations,Wind_Direction_mean
0,2019-01-01,1,Sulphur Dioxide,5.0,NaN,7.0,1.0,4.0,6.0,NaN,...,2.0,5.0,9.0,2019-01-01 00:00:00,11.2375,75.65625,1027.521429,2.58125,16,5.651749
1,2019-01-01,2,Sulphur Dioxide,5.0,9.0,7.0,1.0,5.0,6.0,10.0,...,2.0,3.0,5.0,2019-01-01 01:00:00,11.1000,76.09375,1027.271429,3.07500,16,5.576745
2,2019-01-01,3,Sulphur Dioxide,5.0,8.0,7.0,1.0,3.0,5.0,10.0,...,2.0,2.0,3.0,2019-01-01 02:00:00,10.9500,76.40000,1027.221429,2.94375,16,6.254531
3,2019-01-01,4,Sulphur Dioxide,5.0,7.0,7.0,1.0,4.0,4.0,10.0,...,2.0,2.0,3.0,2019-01-01 03:00:00,10.8250,77.00000,1026.685714,2.83750,16,6.606928
4,2019-01-01,5,Sulphur Dioxide,5.0,8.0,7.0,2.0,3.0,5.0,10.0,...,2.0,2.0,3.0,2019-01-01 04:00:00,10.7875,77.22500,1026.342857,3.03125,16,6.688085

In [9]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 184128
Columns: 26

In [10]:
df.columns

Index(['DATE', 'HOUR', 'POLLUTANT', 'SHATIN', 'TSUEN WAN', 'CENTRAL',
       'EASTERN', 'KWUN TONG', 'TUEN MUN', 'TUNG CHUNG', 'SHAM SHUI PO',
       'SOUTHERN', 'YUEN LONG', 'CENTRAL/WESTERN', 'KWAI CHUNG',
       'TSEUNG KWAN O', 'TAI PO', 'MONG KOK', 'CAUSEWAY BAY', 'TIMESTAMP',
       'Temperature_mean', 'Humidity_mean', 'Sea_Level_Pressure_mean',
       'Wind_Speed_mean', 'Available_Stations', 'Wind_Direction_mean'],
      dtype='str')

In [11]:
df.isnull().sum()

DATE                           0
HOUR                           0
POLLUTANT                      0
SHATIN                     31864
TSUEN WAN                   6027
CENTRAL                     3955
EASTERN                    56220
KWUN TONG                  31130
TUEN MUN                    3188
TUNG CHUNG                  6024
SHAM SHUI PO               31427
SOUTHERN                   95277
YUEN LONG                   6139
CENTRAL/WESTERN            29297
KWAI CHUNG                 30090
TSEUNG KWAN O               3301
TAI PO                     29370
MONG KOK                    4156
CAUSEWAY BAY                4989
TIMESTAMP                      0
Temperature_mean               0
Humidity_mean                  0
Sea_Level_Pressure_mean        0
Wind_Speed_mean                0
Available_Stations             0
Wind_Direction_mean            0
dtype: int64

In [12]:
df["POLLUTANT"].unique()

<StringArray>
[                  'Sulphur Dioxide', 'Respirable Suspended Particulates',
      'Fine Suspended Particulates ',                   'Nitrogen Oxides',
                  'Nitrogen Dioxide',                   'Carbon Monoxide',
                             'Ozone']
Length: 7, dtype: str

In [13]:
station_columns = [
    "SHATIN", "TSUEN WAN", "CENTRAL", "EASTERN",
    "KWUN TONG", "TUEN MUN", "TUNG CHUNG", "SHAM SHUI PO",
    "SOUTHERN", "YUEN LONG", "CENTRAL/WESTERN", "KWAI CHUNG",
    "TSEUNG KWAN O", "TAI PO", "MONG KOK", "CAUSEWAY BAY"
]

len(station_columns)

16

In [14]:
weather_columns = [
    "Temperature_mean",
    "Humidity_mean",
    "Sea_Level_Pressure_mean",
    "Wind_Speed_mean",
    "Available_Stations",
    "Wind_Direction_mean"
]

df[weather_columns].head()

,Temperature_mean,Humidity_mean,Sea_Level_Pressure_mean,Wind_Speed_mean,Available_Stations,Wind_Direction_mean
0,11.2375,75.65625,1027.521429,2.58125,16,5.651749
1,11.1000,76.09375,1027.271429,3.07500,16,5.576745
2,10.9500,76.40000,1027.221429,2.94375,16,6.254531
3,10.8250,77.00000,1026.685714,2.83750,16,6.606928
4,10.7875,77.22500,1026.342857,3.03125,16,6.688085

In [15]:
df["POLLUTANT"].unique()

<StringArray>
[                  'Sulphur Dioxide', 'Respirable Suspended Particulates',
      'Fine Suspended Particulates ',                   'Nitrogen Oxides',
                  'Nitrogen Dioxide',                   'Carbon Monoxide',
                             'Ozone']
Length: 7, dtype: str

In [16]:
len(df["POLLUTANT"].unique())

7

In [17]:
df["POLLUTANT"].value_counts()

POLLUTANT
Sulphur Dioxide                      26304
Respirable Suspended Particulates    26304
Fine Suspended Particulates          26304
Nitrogen Oxides                      26304
Nitrogen Dioxide                     26304
Carbon Monoxide                      26304
Ozone                                26304
Name: count, dtype: int64

In [18]:
station_columns = [
    "SHATIN",
    "TSUEN WAN",
    "CENTRAL",
    "EASTERN",
    "KWUN TONG",
    "TUEN MUN",
    "TUNG CHUNG",
    "SHAM SHUI PO",
    "SOUTHERN",
    "YUEN LONG",
    "CENTRAL/WESTERN",
    "KWAI CHUNG",
    "TSEUNG KWAN O",
    "TAI PO",
    "MONG KOK",
    "CAUSEWAY BAY"
]

print("Number of stations:", len(station_columns))

Number of stations: 16

In [19]:
df[station_columns].head()

,SHATIN,TSUEN WAN,CENTRAL,EASTERN,KWUN TONG,TUEN MUN,TUNG CHUNG,SHAM SHUI PO,SOUTHERN,YUEN LONG,CENTRAL/WESTERN,KWAI CHUNG,TSEUNG KWAN O,TAI PO,MONG KOK,CAUSEWAY BAY
0,5.0,NaN,7.0,1.0,4.0,6.0,NaN,3.0,NaN,NaN,3.0,5.0,4.0,2.0,5.0,9.0
1,5.0,9.0,7.0,1.0,5.0,6.0,10.0,4.0,NaN,8.0,2.0,4.0,4.0,2.0,3.0,5.0
2,5.0,8.0,7.0,1.0,3.0,5.0,10.0,3.0,NaN,7.0,2.0,4.0,4.0,2.0,2.0,3.0
3,5.0,7.0,7.0,1.0,4.0,4.0,10.0,16.0,NaN,7.0,3.0,4.0,4.0,2.0,2.0,3.0
4,5.0,8.0,7.0,2.0,3.0,5.0,10.0,6.0,NaN,7.0,3.0,4.0,4.0,2.0,2.0,3.0

In [20]:
weather_columns = [
    "Temperature_mean",
    "Humidity_mean",
    "Sea_Level_Pressure_mean",
    "Wind_Speed_mean",
    "Available_Stations",
    "Wind_Direction_mean"
]

print("Number of weather features:", len(weather_columns))
print("\nWeather features:")
for col in weather_columns:
    print("-", col)

Number of weather features: 6

Weather features:
- Temperature_mean
- Humidity_mean
- Sea_Level_Pressure_mean
- Wind_Speed_mean
- Available_Stations
- Wind_Direction_mean

In [21]:
df[weather_columns].head()

,Temperature_mean,Humidity_mean,Sea_Level_Pressure_mean,Wind_Speed_mean,Available_Stations,Wind_Direction_mean
0,11.2375,75.65625,1027.521429,2.58125,16,5.651749
1,11.1000,76.09375,1027.271429,3.07500,16,5.576745
2,10.9500,76.40000,1027.221429,2.94375,16,6.254531
3,10.8250,77.00000,1026.685714,2.83750,16,6.606928
4,10.7875,77.22500,1026.342857,3.03125,16,6.688085

In [22]:
import pandas as pd

file_path = "../Data/raw data/air_weather_hourly_2019_2021 (2).csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 184128
Columns: 26

In [23]:
df.head()

,DATE,HOUR,POLLUTANT,SHATIN,TSUEN WAN,CENTRAL,EASTERN,KWUN TONG,TUEN MUN,TUNG CHUNG,...,TAI PO,MONG KOK,CAUSEWAY BAY,TIMESTAMP,Temperature_mean,Humidity_mean,Sea_Level_Pressure_mean,Wind_Speed_mean,Available_Stations,Wind_Direction_mean
0,2019-01-01,1,Sulphur Dioxide,5.0,NaN,7.0,1.0,4.0,6.0,NaN,...,2.0,5.0,9.0,2019-01-01 00:00:00,11.2375,75.65625,1027.521429,2.58125,16,5.651749
1,2019-01-01,2,Sulphur Dioxide,5.0,9.0,7.0,1.0,5.0,6.0,10.0,...,2.0,3.0,5.0,2019-01-01 01:00:00,11.1000,76.09375,1027.271429,3.07500,16,5.576745
2,2019-01-01,3,Sulphur Dioxide,5.0,8.0,7.0,1.0,3.0,5.0,10.0,...,2.0,2.0,3.0,2019-01-01 02:00:00,10.9500,76.40000,1027.221429,2.94375,16,6.254531
3,2019-01-01,4,Sulphur Dioxide,5.0,7.0,7.0,1.0,4.0,4.0,10.0,...,2.0,2.0,3.0,2019-01-01 03:00:00,10.8250,77.00000,1026.685714,2.83750,16,6.606928
4,2019-01-01,5,Sulphur Dioxide,5.0,8.0,7.0,2.0,3.0,5.0,10.0,...,2.0,2.0,3.0,2019-01-01 04:00:00,10.7875,77.22500,1026.342857,3.03125,16,6.688085

# code

In [27]:
# STEP 5: Check Timestamp and Duplicate Records

# Convert TIMESTAMP column to datetime format
df["TIMESTAMP"] = pd.to_datetime(df["TIMESTAMP"])

# Check first and last timestamp
print("First Timestamp:", df["TIMESTAMP"].min())
print("Last Timestamp:", df["TIMESTAMP"].max())

# Check total unique timestamps
print("Unique Timestamps:", df["TIMESTAMP"].nunique())

# Check duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

# Check duplicate combinations of TIMESTAMP + POLLUTANT
print(
    "Duplicate TIMESTAMP + POLLUTANT:",
    df.duplicated(subset=["TIMESTAMP", "POLLUTANT"]).sum()
)

First Timestamp: 2019-01-01 00:00:00
Last Timestamp: 2021-12-31 23:00:00
Unique Timestamps: 26304
Duplicate Rows: 0
Duplicate TIMESTAMP + POLLUTANT: 0

In [28]:
# STEP 6: Check Pollutant Distribution

print("Number of pollutants:", df["POLLUTANT"].nunique())

print("\nPollutants:")
for pollutant in df["POLLUTANT"].unique():
    print("-", pollutant)

print("\nRows for each pollutant:")
print(df["POLLUTANT"].value_counts())

Number of pollutants: 7

Pollutants:
- Sulphur Dioxide
- Respirable Suspended Particulates
- Fine Suspended Particulates
- Nitrogen Oxides
- Nitrogen Dioxide
- Carbon Monoxide
- Ozone

Rows for each pollutant:
POLLUTANT
Sulphur Dioxide                      26304
Respirable Suspended Particulates    26304
Fine Suspended Particulates          26304
Nitrogen Oxides                      26304
Nitrogen Dioxide                     26304
Carbon Monoxide                      26304
Ozone                                26304
Name: count, dtype: int64

In [29]:
# STEP 7: Missing Values Analysis

missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": missing_percentage
})

missing_table = missing_table.sort_values(
    by="Missing_Count",
    ascending=False
)

missing_table

                         Missing_Count  Missing_Percentage
SOUTHERN                         95277           51.744982
EASTERN                          56220           30.533107
SHATIN                           31864           17.305353
SHAM SHUI PO                     31427           17.068018
KWUN TONG                        31130           16.906717
KWAI CHUNG                       30090           16.341893
TAI PO                           29370           15.950860
CENTRAL/WESTERN                  29297           15.911214
YUEN LONG                         6139            3.334094
TSUEN WAN                         6027            3.273266
TUNG CHUNG                        6024            3.271637
CAUSEWAY BAY                      4989            2.709528
MONG KOK                          4156            2.257125
CENTRAL                           3955            2.147962
TSEUNG KWAN O                     3301            1.792775
TUEN MUN                          3188            1.731404
DATE                                 0            0.000000
HOUR                                 0            0.000000
POLLUTANT                            0            0.000000
TIMESTAMP                            0            0.000000
Temperature_mean                     0            0.000000
Humidity_mean                        0            0.000000
Sea_Level_Pressure_mean              0            0.000000
Wind_Speed_mean                      0            0.000000
Available_Stations                   0            0.000000
Wind_Direction_mean                  0            0.000000

# Data Cleaning

In [5]:
import pandas as pd

In [8]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles in this folder:")
for file in os.listdir():
    print(file)

Current folder:
E:\Edge_air_pollution imputation\Notebook

Files in this folder:
.gitkeep
.ipynb_checkpoints
01_data_exploration.ipynb

In [10]:
import os

# Current folder se ek level upar jaakar file search karna
parent_folder = os.path.dirname(os.getcwd())

print("Searching in:")
print(parent_folder)

print("\nMatching files:")

found_files = []

for root, dirs, files in os.walk(parent_folder):
    for file in files:
        if "air_weather_hourly_2019_2021" in file.lower():
            full_path = os.path.join(root, file)
            found_files.append(full_path)
            print(full_path)

print("\nTotal matching files found:", len(found_files))

Searching in:
E:\Edge_air_pollution imputation

Matching files:
E:\Edge_air_pollution imputation\Data\raw data\air_weather_hourly_2019_2021 (2).csv

Total matching files found: 1

In [11]:
# STEP 11.1A — Load Raw Dataset

import pandas as pd

file_path = r"E:\Edge_air_pollution imputation\Data\raw data\air_weather_hourly_2019_2021 (2).csv"

df = pd.read_csv(file_path)

print("Data loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Data loaded successfully!
Rows: 184128
Columns: 26

In [12]:
# STEP 11.1B — Verify Loaded Data

print("First 5 rows:")
display(df.head())

print("\nColumn names:")
print(df.columns.tolist())

print("\nData shape:")
print(df.shape)

First 5 rows:

,DATE,HOUR,POLLUTANT,SHATIN,TSUEN WAN,CENTRAL,EASTERN,KWUN TONG,TUEN MUN,TUNG CHUNG,...,TAI PO,MONG KOK,CAUSEWAY BAY,TIMESTAMP,Temperature_mean,Humidity_mean,Sea_Level_Pressure_mean,Wind_Speed_mean,Available_Stations,Wind_Direction_mean
0,2019-01-01,1,Sulphur Dioxide,5.0,NaN,7.0,1.0,4.0,6.0,NaN,...,2.0,5.0,9.0,2019-01-01 00:00:00,11.2375,75.65625,1027.521429,2.58125,16,5.651749
1,2019-01-01,2,Sulphur Dioxide,5.0,9.0,7.0,1.0,5.0,6.0,10.0,...,2.0,3.0,5.0,2019-01-01 01:00:00,11.1000,76.09375,1027.271429,3.07500,16,5.576745
2,2019-01-01,3,Sulphur Dioxide,5.0,8.0,7.0,1.0,3.0,5.0,10.0,...,2.0,2.0,3.0,2019-01-01 02:00:00,10.9500,76.40000,1027.221429,2.94375,16,6.254531
3,2019-01-01,4,Sulphur Dioxide,5.0,7.0,7.0,1.0,4.0,4.0,10.0,...,2.0,2.0,3.0,2019-01-01 03:00:00,10.8250,77.00000,1026.685714,2.83750,16,6.606928
4,2019-01-01,5,Sulphur Dioxide,5.0,8.0,7.0,2.0,3.0,5.0,10.0,...,2.0,2.0,3.0,2019-01-01 04:00:00,10.7875,77.22500,1026.342857,3.03125,16,6.688085

Column names:
['DATE', 'HOUR', 'POLLUTANT', 'SHATIN', 'TSUEN WAN', 'CENTRAL', 'EASTERN', 'KWUN TONG', 'TUEN MUN', 'TUNG CHUNG', 'SHAM SHUI PO', 'SOUTHERN', 'YUEN LONG', 'CENTRAL/WESTERN', 'KWAI CHUNG', 'TSEUNG KWAN O', 'TAI PO', 'MONG KOK', 'CAUSEWAY BAY', 'TIMESTAMP', 'Temperature_mean', 'Humidity_mean', 'Sea_Level_Pressure_mean', 'Wind_Speed_mean', 'Available_Stations', 'Wind_Direction_mean']

Data shape:
(184128, 26)

In [13]:
# STEP 11.2 — Check Data Types

print("Data Types of all columns:\n")

print(df.dtypes)

Data Types of all columns:

DATE                           str
HOUR                         int64
POLLUTANT                      str
SHATIN                     float64
TSUEN WAN                  float64
CENTRAL                    float64
EASTERN                    float64
KWUN TONG                  float64
TUEN MUN                   float64
TUNG CHUNG                 float64
SHAM SHUI PO               float64
SOUTHERN                   float64
YUEN LONG                  float64
CENTRAL/WESTERN            float64
KWAI CHUNG                 float64
TSEUNG KWAN O              float64
TAI PO                     float64
MONG KOK                   float64
CAUSEWAY BAY               float64
TIMESTAMP                      str
Temperature_mean           float64
Humidity_mean              float64
Sea_Level_Pressure_mean    float64
Wind_Speed_mean            float64
Available_Stations           int64
Wind_Direction_mean        float64
dtype: object

In [14]:
# STEP 11.3 — Convert DATE and TIMESTAMP to Datetime

df["DATE"] = pd.to_datetime(df["DATE"], errors="coerce")
df["TIMESTAMP"] = pd.to_datetime(df["TIMESTAMP"], errors="coerce")

print("DATE data type:", df["DATE"].dtype)
print("TIMESTAMP data type:", df["TIMESTAMP"].dtype)

DATE data type: datetime64[us]
TIMESTAMP data type: datetime64[us]

In [15]:
# STEP 11.3A — Check Invalid Date/Timestamp Values

print("Invalid DATE values:", df["DATE"].isna().sum())
print("Invalid TIMESTAMP values:", df["TIMESTAMP"].isna().sum())

Invalid DATE values: 0
Invalid TIMESTAMP values: 0

In [16]:
# STEP 11.4 — Check Missing Values

missing_values = df.isnull().sum()

print("Missing values in each column:\n")
print(missing_values)

Missing values in each column:

DATE                           0
HOUR                           0
POLLUTANT                      0
SHATIN                     31864
TSUEN WAN                   6027
CENTRAL                     3955
EASTERN                    56220
KWUN TONG                  31130
TUEN MUN                    3188
TUNG CHUNG                  6024
SHAM SHUI PO               31427
SOUTHERN                   95277
YUEN LONG                   6139
CENTRAL/WESTERN            29297
KWAI CHUNG                 30090
TSEUNG KWAN O               3301
TAI PO                     29370
MONG KOK                    4156
CAUSEWAY BAY                4989
TIMESTAMP                      0
Temperature_mean               0
Humidity_mean                  0
Sea_Level_Pressure_mean        0
Wind_Speed_mean                0
Available_Stations             0
Wind_Direction_mean            0
dtype: int64

In [17]:
# STEP 11.5 — Check Duplicate Rows

duplicate_rows = df.duplicated().sum()

print("Total duplicate rows:", duplicate_rows)

Total duplicate rows: 0

In [18]:
# STEP 11.6 — Check Duplicate Timestamp + Pollutant Combinations

duplicate_timestamp_pollutant = df.duplicated(
    subset=["TIMESTAMP", "POLLUTANT"]
).sum()

print("Duplicate TIMESTAMP + POLLUTANT combinations:",
      duplicate_timestamp_pollutant)

Duplicate TIMESTAMP + POLLUTANT combinations: 0

In [19]:
# STEP 11.7 — Validate HOUR Values

print("Minimum HOUR value:", df["HOUR"].min())
print("Maximum HOUR value:", df["HOUR"].max())

invalid_hours = (~df["HOUR"].between(0, 23)).sum()

print("Invalid HOUR values:", invalid_hours)

Minimum HOUR value: 1
Maximum HOUR value: 24
Invalid HOUR values: 7672

In [20]:
# STEP 11.7A — Check HOUR Distribution

hour_counts = df["HOUR"].value_counts().sort_index()

print("HOUR values and their counts:\n")
print(hour_counts)

HOUR values and their counts:

HOUR
1     7672
2     7672
3     7672
4     7672
5     7672
6     7672
7     7672
8     7672
9     7672
10    7672
11    7672
12    7672
13    7672
14    7672
15    7672
16    7672
17    7672
18    7672
19    7672
20    7672
21    7672
22    7672
23    7672
24    7672
Name: count, dtype: int64

In [21]:
# STEP 11.8 — Validate Pollutant Categories

pollutants = df["POLLUTANT"].unique()

print("Number of unique pollutants:", len(pollutants))
print("\nPollutants:")
print(pollutants)

Number of unique pollutants: 7

Pollutants:
<StringArray>
[                  'Sulphur Dioxide', 'Respirable Suspended Particulates',
      'Fine Suspended Particulates ',                   'Nitrogen Oxides',
                  'Nitrogen Dioxide',                   'Carbon Monoxide',
                             'Ozone']
Length: 7, dtype: str

In [22]:
# STEP 11.8A — Remove Extra Spaces from Pollutant Names

df["POLLUTANT"] = df["POLLUTANT"].str.strip()

print("Pollutants after cleaning:")
print(df["POLLUTANT"].unique())

Pollutants after cleaning:
<StringArray>
[                  'Sulphur Dioxide', 'Respirable Suspended Particulates',
       'Fine Suspended Particulates',                   'Nitrogen Oxides',
                  'Nitrogen Dioxide',                   'Carbon Monoxide',
                             'Ozone']
Length: 7, dtype: str

In [23]:
# STEP 11.9 — Check Negative Pollution Values

station_columns = [
    "SHATIN", "TSUEN WAN", "CENTRAL", "EASTERN",
    "KWUN TONG", "TUEN MUN", "TUNG CHUNG", "SHAM SHUI PO",
    "SOUTHERN", "YUEN LONG", "CENTRAL/WESTERN", "KWAI CHUNG",
    "TSEUNG KWAN O", "TAI PO", "MONG KOK", "CAUSEWAY BAY"
]

negative_values = (df[station_columns] < 0).sum()

print("Negative values in each station column:\n")
print(negative_values)

print("\nTotal negative values:",
      negative_values.sum())

Negative values in each station column:

SHATIN             0
TSUEN WAN          0
CENTRAL            0
EASTERN            0
KWUN TONG          0
TUEN MUN           0
TUNG CHUNG         0
SHAM SHUI PO       0
SOUTHERN           0
YUEN LONG          0
CENTRAL/WESTERN    0
KWAI CHUNG         0
TSEUNG KWAN O      0
TAI PO             0
MONG KOK           0
CAUSEWAY BAY       0
dtype: int64

Total negative values: 0

In [24]:
# STEP 11.10 — Verify 7 Pollutants per Timestamp

pollutants_per_timestamp = df.groupby("TIMESTAMP")["POLLUTANT"].nunique()

print("Minimum pollutants per timestamp:",
      pollutants_per_timestamp.min())

print("Maximum pollutants per timestamp:",
      pollutants_per_timestamp.max())

invalid_timestamps = (pollutants_per_timestamp != 7).sum()

print("Timestamps without exactly 7 pollutants:",
      invalid_timestamps)

Minimum pollutants per timestamp: 7
Maximum pollutants per timestamp: 7
Timestamps without exactly 7 pollutants: 0

In [25]:
# STEP 11.11 — Verify Unique Timestamps

unique_timestamps = df["TIMESTAMP"].nunique()

print("Number of unique timestamps:", unique_timestamps)

Number of unique timestamps: 26304

In [26]:
# STEP 11.12 — Check Hourly Time Continuity

timestamps = df["TIMESTAMP"].drop_duplicates().sort_values()

time_difference = timestamps.diff().dropna()

expected_difference = pd.Timedelta(hours=1)

missing_hour_gaps = (time_difference != expected_difference).sum()

print("Total timestamps:", len(timestamps))
print("Unexpected time gaps:", missing_hour_gaps)

Total timestamps: 26304
Unexpected time gaps: 0

In [27]:
# STEP 11.13 — Save Cleaned Dataset

import os

# Create processed-data folder if it does not already exist
processed_folder = r"E:\Edge_air_pollution imputation\Data\processed"
os.makedirs(processed_folder, exist_ok=True)

# Output file path
cleaned_file_path = os.path.join(
    processed_folder,
    "air_weather_cleaned_2019_2021.csv"
)

# Save cleaned dataframe
df.to_csv(cleaned_file_path, index=False)

print("Cleaned dataset saved successfully!")
print("File path:", cleaned_file_path)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Cleaned dataset saved successfully!
File path: E:\Edge_air_pollution imputation\Data\processed\air_weather_cleaned_2019_2021.csv
Rows: 184128
Columns: 26

# Missing-Value Masking

In [2]:
import pandas as pd

file_path = "../Data/raw data/air_weather_hourly_2019_2021 (2).csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 184128
Columns: 26

In [3]:
# STEP 3.1 — Check original missing values

station_columns = [
    "SHATIN", "TSUEN WAN", "CENTRAL", "EASTERN",
    "KWUN TONG", "TUEN MUN", "TUNG CHUNG", "SHAM SHUI PO",
    "SOUTHERN", "YUEN LONG", "CENTRAL/WESTERN", "KWAI CHUNG",
    "TSEUNG KWAN O", "TAI PO", "MONG KOK", "CAUSEWAY BAY"
]

original_missing = df[station_columns].isna().sum()

print("Missing values in each station:")
print(original_missing)

print("\nTotal original missing values:", original_missing.sum())

print("\nTotal station values:", df[station_columns].size)

print(
    "\nOriginal missing percentage:",
    round((original_missing.sum() / df[station_columns].size) * 100, 2),
    "%"
)

Missing values in each station:
SHATIN             31864
TSUEN WAN           6027
CENTRAL             3955
EASTERN            56220
KWUN TONG          31130
TUEN MUN            3188
TUNG CHUNG          6024
SHAM SHUI PO       31427
SOUTHERN           95277
YUEN LONG           6139
CENTRAL/WESTERN    29297
KWAI CHUNG         30090
TSEUNG KWAN O       3301
TAI PO             29370
MONG KOK            4156
CAUSEWAY BAY        4989
dtype: int64

Total original missing values: 372454

Total station values: 2946048

Original missing percentage: 12.64 %

In [4]:
# STEP 3.2 — Create Observed-Value Mask

# 1 = value available (observed)
# 0 = value missing

observed_mask = df[station_columns].notna().astype("int8")

print("Observed-value mask created successfully!")

print("\nMask shape:", observed_mask.shape)

print("\nFirst 5 rows of mask:")
print(observed_mask.head())

print("\nMask values:")
print(observed_mask.stack().value_counts())

Observed-value mask created successfully!

Mask shape: (184128, 16)

First 5 rows of mask:
   SHATIN  TSUEN WAN  CENTRAL  EASTERN  KWUN TONG  TUEN MUN  TUNG CHUNG  \
0       1          0        1        1          1         1           0
1       1          1        1        1          1         1           1
2       1          1        1        1          1         1           1
3       1          1        1        1          1         1           1
4       1          1        1        1          1         1           1

   SHAM SHUI PO  SOUTHERN  YUEN LONG  CENTRAL/WESTERN  KWAI CHUNG  \
0             1         0          0                1           1
1             1         0          1                1           1
2             1         0          1                1           1
3             1         0          1                1           1
4             1         0          1                1           1

   TSEUNG KWAN O  TAI PO  MONG KOK  CAUSEWAY BAY
0              1       1         1             1
1              1       1         1             1
2              1       1         1             1
3              1       1         1             1
4              1       1         1             1

Mask values:
1    2573594
0     372454
Name: count, dtype: int64

In [5]:
# STEP 3.3 — Verify Observed Mask

# Check:
# Mask = 0 should correspond to NaN
# Mask = 1 should correspond to available value

mask_zero = (observed_mask == 0)
mask_one = (observed_mask == 1)

# Values that are missing but mask says 1
error_missing = df[station_columns].isna() & mask_one

# Values that are available but mask says 0
error_observed = df[station_columns].notna() & mask_zero

print("Missing values incorrectly marked as 1:", error_missing.sum().sum())
print("Observed values incorrectly marked as 0:", error_observed.sum().sum())

if error_missing.sum().sum() == 0 and error_observed.sum().sum() == 0:
    print("\nMask verification successful! ✅")
else:
    print("\nMask verification failed! ❌")

Missing values incorrectly marked as 1: 0
Observed values incorrectly marked as 0: 0

Mask verification successful! ✅

In [9]:
# STEP 3.4 — Create Artificial Missing Mask

import numpy as np
import pandas as pd

# Reproducible result
np.random.seed(42)

# Artificial missingness rate
missing_rate = 0.20

# Mask ko writable NumPy array mein convert karo
mask_array = observed_mask.to_numpy(copy=True)

# Random numbers generate karo
random_values = np.random.random(mask_array.shape)

# Sirf originally observed values mein se 20% select karo
artificial_positions = (
    (mask_array == 1) &
    (random_values < missing_rate)
)

# Selected values ko artificially missing mark karo
mask_array[artificial_positions] = 0

# NumPy array ko wapas DataFrame mein convert karo
artificial_mask = pd.DataFrame(
    mask_array,
    index=observed_mask.index,
    columns=observed_mask.columns
)

# Results
original_observed = (observed_mask.to_numpy() == 1).sum()
artificially_masked = artificial_positions.sum()

print("Artificial masking completed successfully! ✅")

print("\nOriginal observed values:", original_observed)
print("Artificially masked values:", artificially_masked)

print(
    "Actual artificial missing rate:",
    round((artificially_masked / original_observed) * 100, 2),
    "%"
)

print("\nFinal mask counts:")
print(artificial_mask.stack().value_counts())

Artificial masking completed successfully! ✅

Original observed values: 2573594
Artificially masked values: 513824
Actual artificial missing rate: 19.97 %

Final mask counts:
1    2059770
0     886278
Name: count, dtype: int64

 # Sliding-Window Dataset

In [3]:
# STEP 4.0 — Restore Dataset and Mask Variables

import pandas as pd
import numpy as np

# Dataset load
file_path = "../Data/raw data/air_weather_hourly_2019_2021 (2).csv"
df = pd.read_csv(file_path)

# 16 station columns
station_columns = [
    "SHATIN", "TSUEN WAN", "CENTRAL", "EASTERN",
    "KWUN TONG", "TUEN MUN", "TUNG CHUNG", "SHAM SHUI PO",
    "SOUTHERN", "YUEN LONG", "CENTRAL/WESTERN", "KWAI CHUNG",
    "TSEUNG KWAN O", "TAI PO", "MONG KOK", "CAUSEWAY BAY"
]

# Original observed mask
observed_mask = df[station_columns].notna().astype("int8")

# Recreate the same 20% artificial mask
np.random.seed(42)

missing_rate = 0.20

mask_array = observed_mask.to_numpy(copy=True)

random_values = np.random.random(mask_array.shape)

artificial_positions = (
    (mask_array == 1) &
    (random_values < missing_rate)
)

mask_array[artificial_positions] = 0

artificial_mask = pd.DataFrame(
    mask_array,
    index=observed_mask.index,
    columns=observed_mask.columns
)

print("Dataset and mask variables restored successfully! ✅")

print("\nDataset shape:", df.shape)
print("Observed mask shape:", observed_mask.shape)
print("Artificial mask shape:", artificial_mask.shape)

print("\nArtificially masked values:",
      artificial_positions.sum())

Dataset and mask variables restored successfully! ✅

Dataset shape: (184128, 26)
Observed mask shape: (184128, 16)
Artificial mask shape: (184128, 16)

Artificially masked values: 513824

In [4]:
# STEP 4.1 — Check Time and Pollutant Structure

print("Total rows:", len(df))

print("\nUnique timestamps:", df["TIMESTAMP"].nunique())

print("\nUnique pollutants:")
print(df["POLLUTANT"].unique())

print("\nNumber of pollutants:", df["POLLUTANT"].nunique())

print("\nFirst 10 timestamps:")
print(df["TIMESTAMP"].head(10))

print("\nRows per timestamp:")
print(df.groupby("TIMESTAMP").size().value_counts().sort_index())

Total rows: 184128

Unique timestamps: 26304

Unique pollutants:
<StringArray>
[                  'Sulphur Dioxide', 'Respirable Suspended Particulates',
      'Fine Suspended Particulates ',                   'Nitrogen Oxides',
                  'Nitrogen Dioxide',                   'Carbon Monoxide',
                             'Ozone']
Length: 7, dtype: str

Number of pollutants: 7

First 10 timestamps:
0    2019-01-01 00:00:00
1    2019-01-01 01:00:00
2    2019-01-01 02:00:00
3    2019-01-01 03:00:00
4    2019-01-01 04:00:00
5    2019-01-01 05:00:00
6    2019-01-01 06:00:00
7    2019-01-01 07:00:00
8    2019-01-01 08:00:00
9    2019-01-01 09:00:00
Name: TIMESTAMP, dtype: str

Rows per timestamp:
7    26304
Name: count, dtype: int64

In [5]:
# STEP 4.2 — Create Time × Station × Feature Tensor

import numpy as np
import pandas as pd

# --------------------------------------------------
# 1. Pollution features
# --------------------------------------------------

pollutant_order = [
    "Sulphur Dioxide",
    "Respirable Suspended Particulates",
    "Fine Suspended Particulates ",
    "Nitrogen Oxides",
    "Nitrogen Dioxide",
    "Carbon Monoxide",
    "Ozone"
]

# --------------------------------------------------
# 2. Weather features
# --------------------------------------------------

weather_columns = [
    "Temperature_mean",
    "Humidity_mean",
    "Sea_Level_Pressure_mean",
    "Wind_Speed_mean",
    "Available_Stations",
    "Wind_Direction_mean"
]

# --------------------------------------------------
# 3. Sort data by timestamp
# --------------------------------------------------

df["TIMESTAMP"] = pd.to_datetime(df["TIMESTAMP"])

df = df.sort_values("TIMESTAMP").reset_index(drop=True)

# Unique timestamps
timestamps = df["TIMESTAMP"].drop_duplicates().sort_values().reset_index(drop=True)

# --------------------------------------------------
# 4. Create pollution tensor
# Shape = (time, station, pollution_features)
# --------------------------------------------------

pollution_data = np.zeros(
    (len(timestamps), len(station_columns), len(pollutant_order)),
    dtype=np.float32
)

for feature_index, pollutant in enumerate(pollutant_order):

    pollutant_df = (
        df[df["POLLUTANT"] == pollutant]
        .sort_values("TIMESTAMP")
    )

    pollution_data[:, :, feature_index] = (
        pollutant_df[station_columns].to_numpy(dtype=np.float32)
    )

# --------------------------------------------------
# 5. Create weather data
# One row per timestamp
# --------------------------------------------------

weather_df = (
    df[["TIMESTAMP"] + weather_columns]
    .drop_duplicates("TIMESTAMP")
    .sort_values("TIMESTAMP")
)

weather_data = weather_df[weather_columns].to_numpy(
    dtype=np.float32
)

# --------------------------------------------------
# 6. Repeat weather features for all 16 stations
# --------------------------------------------------

weather_data = np.repeat(
    weather_data[:, np.newaxis, :],
    len(station_columns),
    axis=1
)

# --------------------------------------------------
# 7. Combine pollution + weather
# --------------------------------------------------

data_tensor = np.concatenate(
    [pollution_data, weather_data],
    axis=2
)

# --------------------------------------------------
# 8. Display final shape
# --------------------------------------------------

print("Tensor created successfully! ✅")

print("\nTensor shape:", data_tensor.shape)

print("\nExpected shape:")
print("(26304, 16, 13)")

print("\nNumber of timestamps:", data_tensor.shape[0])
print("Number of stations:", data_tensor.shape[1])
print("Number of features:", data_tensor.shape[2])

Tensor created successfully! ✅

Tensor shape: (26304, 16, 13)

Expected shape:
(26304, 16, 13)

Number of timestamps: 26304
Number of stations: 16
Number of features: 13

In [6]:
# STEP 4.3 — Create 24-Hour Sliding Windows

window_size = 24

num_windows = data_tensor.shape[0] - window_size + 1

sliding_windows = np.empty(
    (num_windows, window_size, len(station_columns), 13),
    dtype=np.float32
)

for i in range(num_windows):
    sliding_windows[i] = data_tensor[
        i:i + window_size
    ]

print("Sliding-window dataset created successfully! ✅")

print("\nWindow size:", window_size, "hours")

print("Number of windows:", sliding_windows.shape[0])

print("Each window shape:", sliding_windows.shape[1:])

print("Final sliding-window shape:", sliding_windows.shape)

print(
    "\nExpected shape:",
    (26304 - 24 + 1, 24, 16, 13)
)

Sliding-window dataset created successfully! ✅

Window size: 24 hours
Number of windows: 26281
Each window shape: (24, 16, 13)
Final sliding-window shape: (26281, 24, 16, 13)

Expected shape: (26281, 24, 16, 13)

In [7]:
# STEP 4.4 — Create 13-Feature Mask Tensor

# Pollution mask:
# 7 pollutant features ke liye artificial_mask use hoga

pollution_mask = np.zeros(
    (len(timestamps), len(station_columns), len(pollutant_order)),
    dtype=np.int8
)

for feature_index, pollutant in enumerate(pollutant_order):

    pollutant_df = (
        df[df["POLLUTANT"] == pollutant]
        .sort_values("TIMESTAMP")
    )

    # Original missing + artificial missing
    pollution_mask[:, :, feature_index] = (
        artificial_mask.loc[
            pollutant_df.index, station_columns
        ].to_numpy(dtype=np.int8)
    )


# Weather mask:
# Weather features mein missing values nahi hain,
# isliye sabko 1 mark karenge.

weather_mask = np.ones(
    (len(timestamps), len(station_columns), len(weather_columns)),
    dtype=np.int8
)


# Combine pollution + weather masks

mask_tensor = np.concatenate(
    [pollution_mask, weather_mask],
    axis=2
)


print("13-feature mask tensor created successfully! ✅")

print("\nMask tensor shape:", mask_tensor.shape)

print("\nExpected shape:")
print("(26304, 16, 13)")

print("\nMask values:")
print(
    pd.Series(mask_tensor.flatten()).value_counts().sort_index()
)

13-feature mask tensor created successfully! ✅

Mask tensor shape: (26304, 16, 13)

Expected shape:
(26304, 16, 13)

Mask values:
0     886278
1    4584954
Name: count, dtype: int64

In [8]:
# STEP 4.5 — Create Sliding-Window Mask

mask_sliding_windows = np.empty(
    (
        num_windows,
        window_size,
        len(station_columns),
        13
    ),
    dtype=np.int8
)

for i in range(num_windows):
    mask_sliding_windows[i] = mask_tensor[
        i:i + window_size
    ]

print("Sliding-window mask created successfully! ✅")

print("\nMask window size:", window_size, "hours")

print("Number of mask windows:", mask_sliding_windows.shape[0])

print("Each mask window shape:", mask_sliding_windows.shape[1:])

print(
    "Final mask sliding-window shape:",
    mask_sliding_windows.shape
)

print(
    "\nData windows shape:",
    sliding_windows.shape
)

print(
    "Data and mask shapes match:",
    sliding_windows.shape == mask_sliding_windows.shape
)

Sliding-window mask created successfully! ✅

Mask window size: 24 hours
Number of mask windows: 26281
Each mask window shape: (24, 16, 13)
Final mask sliding-window shape: (26281, 24, 16, 13)

Data windows shape: (26281, 24, 16, 13)
Data and mask shapes match: True